version: '3.7'
services:
  web:
    build: ./front
    container_name: Full-Stack-Vue-Docker-Gabriel-Teixeira
    ports:
     - '3000:3000'
    environment:
      - NODE_ENV=dev
    volumes:
      - ./front:/usr/src/app
    command: bash -c 'yarn && yarn dev --host'