FROM golang:1.22.6-alpine

# Instalação do air
RUN apk add --no-cache git && \
  go install github.com/air-verse/air@latest

WORKDIR /app

# Copia o arquivo de configuração do air
COPY .air.toml ./

# Copia os arquivos de dependências
COPY go.mod ./
COPY go.sum ./
RUN go mod download

# Copia o código do projeto
COPY . .

# Comando de entrada para o air
CMD ["air"]