FROM golang:1.22.6-alpine AS builder

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY . ./
RUN go build -o /go-back

FROM alpine:latest
WORKDIR /root/
COPY --from=builder /go-back .

CMD ["./go-back"]