version: '3.9'
 
services:
    app:
        build: .
        image: webapp
        container_name: Frontend-Docker-Gabriel-Teixeira
        ports:
            - '3000:3000'
        environment:
            - NODE_ENV=dev
        volumes:
            - .:/app
            - /app/node_modules